### ISSUE TITLE
Missing Data File

### ISSUE THREAD

**Issue by mobalt** [petralenzini/RedCap2NDA_withCrosswalk#1]
Hi Petra,

There is a file referenced in the code which I can't find. Could you upload it?

https://github.com/petralenzini/RedCap2NDA_withCrosswalk/blob/aa5cba17f3813ae9d5d4d296dbfb72ab2bc0d725/applyHCPDcrosswalk.py#L30-L32

**Comment by petralenzini** [comment]
Hi Moises,
I added Template_Rosetta.csv to this repo, which is an example of the type of information contained in the file pointed to by ndar_fields).  I also sent you by email the actual file...which can't be uploaded here because it is an ID map across systems...Note that this file will ultimately need to be replaced with one that is updated after the list of IDs if finalized for the release, which will require rerunning the program that generates pedigree ids from family data collected monthly by Cindy in BOX, and the randomization function that takes this info and randomly selects a person from this family to be the designated member of the 'unrelated subset'
petra
